### ISSUE TITLE
Explain how the term AI is used in different audiences

### ISSUE THREAD

**Issue by arronlacey** [carpentries-incubator/data-science-ai-senior-researchers#13]
In the introduction I think we should contextualize the use of AI and it's relation to ML. AI is a very high level term that gets used less as you read papers on methodologies etc where ML and sub-types of ML are more common. We should explain why this is.

**Comment by johav** [comment]
Agreed, I will add this. 
Also, _due to the recent developments in automated machine learning techniques it is now possible for biomedical researchers to build competitive machine-learning classifiers without the need for an in-depth understanding of the underlying algorithms._ (which begs for accuracy in the documentation of the applied workflows)
